// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2LUU4X1tnMqm0dg6alSFReUqAgDYoqAA',
    appId: '1:158749555895:web:5ff53dc527f5ffe1f46132',
    messagingSenderId: '158749555895',
    projectId: 'instagram-clone-app-8709e',
    authDomain: 'instagram-clone-app-8709e.firebaseapp.com',
    storageBucket: 'instagram-clone-app-8709e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA91kRDnoIN_aHkUNNEh0Fb_P3dGPWl6Wo',
    appId: '1:158749555895:android:8ed58d943f9a966df46132',
    messagingSenderId: '158749555895',
    projectId: 'instagram-clone-app-8709e',
    storageBucket: 'instagram-clone-app-8709e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_0_xMqNy1XPhf9Ei-G0wBDvbCfhuE3WY',
    appId: '1:158749555895:ios:23afa4727e2c47b8f46132',
    messagingSenderId: '158749555895',
    projectId: 'instagram-clone-app-8709e',
    storageBucket: 'instagram-clone-app-8709e.appspot.com',
    iosClientId: '158749555895-hf9299sdt26jpqqca9ekppvjfr90ppua.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramCloneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_0_xMqNy1XPhf9Ei-G0wBDvbCfhuE3WY',
    appId: '1:158749555895:ios:c4eb91b5b15ca092f46132',
    messagingSenderId: '158749555895',
    projectId: 'instagram-clone-app-8709e',
    storageBucket: 'instagram-clone-app-8709e.appspot.com',
    iosClientId: '158749555895-g357s462k9it2rm9o77jda41248fucqa.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramCloneApp.RunnerTests',
  );
}
